### ISSUE TITLE
Structuring the code in proper format 

### ISSUE THREAD

**Issue by Aditya-Khaladkar** [Suryansh1720001/Taaveez#10]
### Is your feature request related to a problem? Please describe.

I can structure the code in proper format by dividing it into different packages and also implementing viewmodels for room 

### Additional context

Please assign this issue to me under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @Aditya-Khaladkar 
It is not necessary to proceed with that action. Instead, please consider checking other issues and creating ones that directly contribute to the project's objectives. For more updates, you can follow me on GitHub at @Suryansh1720001.
Thank You
