### ISSUE TITLE
Pop-up question and page heading remains in English despite Hindi content

### ISSUE THREAD

**Issue by ManogjnaSinguluri** [Suryansh1720001/Taaveez#100]
### What happened?

When we set content language to Hindi and start writing a note the page heading "Inventive work" remains in English  and when we go back without saving "Do you want to discard your changes and go back" pop-up question also remains in English 

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to settings and change content language to Hindi
2. On home, Click on add notes option and observe the page heading
3. Write a sample note and Go back without saving 
4. Observe the pop-up question
```

### Expected behavior

The page heading should be "रचनात्मक कार्य" and the pop-up question should be "क्या आप अपने बदलाव को छोड़कर पीछे जाना चाहते हैं"

### Screenshots

![imgpsh_fullsize_anim](https://github.com/Taaveez/Taaveez-android/assets/114799185/6d390e72-5b51-47f6-94d9-116c10ae4a1c)

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

One plus 9R , Android 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManogjnaSinguluri** [comment]
@Suryansh1720001 @Vaibhav2002  I want to work on this issue as a part of Gssoc 2023 .Could you assign this issue to me

**Comment by Vaibhav2002** [comment]
@ManogjnaSinguluri make sure everything in app is in Hindi, if Hindi language is selected in settings.
Assigning it to you.
