### ISSUE TITLE
Adding "Pin the Note" feature to make that note remain at top

### ISSUE THREAD

**Issue by meemanali** [Suryansh1720001/Taaveez#106]
### Is your feature request related to a problem? Please describe.

It may create bad UX, in case there are many notes. 

### Describe the solution you'd like

Creating an option for each note to Pin it at top of other notes. In case of a lot of notes the specific note, which the user wants, will remain at top. 

### Describe alternatives you've considered

Creating a "Pin the Note" option / feature to notes. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukundsolanki** [comment]
Can you assign me this issue, I want to work on this under IWOC24

**Comment by Suryansh1720001** [comment]
I'm assigning you this task for IWOC'24. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me.

And at the time of coding, take care of the UI, and set valuable variable names.
