### ISSUE TITLE
Attach APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [Suryansh1720001/Taaveez#109]
### Is your feature request related to a problem? Please describe.

Currently, your app is only available in Google's walled garden – people without access to that place cannot install your app.

### Describe the solution you'd like

Please attach the signed APK files to their corresponding [releases](https://github.com/Taaveez/Taaveez-android/releases), starting with the current release (no need for historical ones).

### Describe alternatives you've considered

Bring your app to [F-Droid](https://f-droid.org/), which is an open place for Android FOSS apps. This would also add trust, as the F-Droid team will check the app before publishing. It could also be seen as additional measure; with the APKs available at their releases, reproducible builds could be established (I can provide more details on this if you're interested).

### Additional context

It's a pity such a fine and [tracker-free](https://reports.exodus-privacy.eu.org/de/reports/383789/) FOSS app requires an account with one of the largest data collectors just to install it – so providing it by other, free/libre means would be much appreciated!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IzzySoft** [comment]
Any word, @Suryansh1720001 ?

**Comment by Suryansh1720001** [comment]
ok great, it helps me. 
I will add it on F-droid.
