### ISSUE TITLE
Introducing MVVM Architecture in the code

### ISSUE THREAD

**Issue by harsh2907** [Suryansh1720001/Taaveez#11]
### Is your feature request related to a problem? Please describe.

To make a scalable app an Architecture plays a very important role. so to make this project a success we should add a architecture in it.

### Describe the solution you'd like

So I will restructure the existing code in MVVM format. So assign this issue to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @harsh2907 
Can you please explain how transitioning from a Room database to an MVVM project would benefit the project? I would like to understand the advantages and improvements it can bring.

**Comment by harsh2907** [comment]
We are not migrating from room database, mvvm is a pattern to arrange files and workflow in way so that code will be more testable, well organised and also easier to maintain with more features

**Comment by Suryansh1720001** [comment]
Hello @harsh2907,
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this.

**Comment by priyanshu942** [comment]
I would like to work on this issue under Gssoc

**Comment by Suryansh1720001** [comment]
@harsh2907 
Any update regarding the MVVM Architecture?

**Comment by Suryansh1720001** [comment]
@harsh2907 
Okay, but this type of issue has already been raised by Dev on #61. I have already assigned you the issue related to adding dependency injection. You can work on this issue with the MVVM architecture. 
Update me accordingly...

**Comment by Suryansh1720001** [comment]
@harsh2907 
Any Update Harsh!

**Comment by harsh2907** [comment]
I am unable to resolve any issue right now due to some emergency. So please assign all issues to some one else. Thank you for your cooperation.
