### ISSUE TITLE
[style]- Revamping UI

### ISSUE THREAD

**Issue by GitWiz01** [Suryansh1720001/Taaveez#110]
### What's the style idea?

Basic Idea:
- I will revamp the layout correct the theme of the app and add some elements so that the user experience gets enhanced.

Steps:
1. Improving layout by adding separations.
2. Adding a better button style.
3. Making it more interactive by topography principle. 
4. Finally giving the Figma wireframe for different screens of the app.

Also Please add IWOC24 tag 🚀

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hi there! Thanks for your input. Could you please share specific design elements or Figma wireframes you have in mind for the layout revamp and enhanced user experience? This will help me better understand your vision and efficiently address the updates. Looking forward to your response! 🚀

**Comment by GitWiz01** [comment]
I can't find any similar work to what I'm thinking for your app
However, I am leaving my some of my works so that u get an idea of my design ideology.

Synclify UI(old vs new) -https://www.figma.com/file/IqMaTU1KKm5XcD21OZzleZ/Synclify-UI?type=design&mode=design&t=X4f0oR4sCrPHinZY-1

GrabTern Logo(old vs new)- https://github.com/anmode/grabtern-frontend/pull/826

A hackathon project website - https://www.figma.com/file/mkaFlnhiNb1LanwJl3uqFi/CodeJustice-(Copy)?type=design&node-id=0%3A1&mode=design&t=fECRRF00Tta514H2-1

**Comment by GitWiz01** [comment]
@Suryansh1720001 please checkout the work

**Comment by Suryansh1720001** [comment]
@GitWiz01 
I'm not satisfied with the work you provided in the link. The current app design is better than what was presented. I am closing the issue now.

**Comment by GitWiz01** [comment]
Fine no problem @Suryansh1720001 
Hope to see the app rock in the near future and more valuable contributions to be made 🤞🚀
