### ISSUE TITLE
Improving splash screen 

### ISSUE THREAD

**Issue by harsh2907** [Suryansh1720001/Taaveez#12]
### Is your feature request related to a problem? Please describe.

We can improve the splash screen by adding some animation in it to make it more attractive as the current one doesn't look decent 

### Describe the solution you'd like

So I will make splash screen for the app. So assign this issue to me under GSSOC'23 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MUDITJAIN2** [comment]
Please assign this issue to me under Gssoc'23.

**Comment by Suryansh1720001** [comment]
Hello,
Kindly provide a template or example animation for the splash screen. So that I'll assign you the task accordingly.
Thank You

**Comment by Suryansh1720001** [comment]
@harsh2907 @MUDITJAIN2 
Provide me the update.

**Comment by Suryansh1720001** [comment]
@harsh2907 
I am dismissing this issue, as you are not actively involved in it.
