### ISSUE TITLE
Font Change and Constrained Layout implementation improvement

### ISSUE THREAD

**Issue by Shreyaskr1409** [Suryansh1720001/Taaveez#121]
### What's the style idea?

We need to improve the implementation of constrains of elements along with margins and paddings. There are places where constrained layout isn't implemented resulting in few buttons getting misplaced. I would like to work on this issue, unless the UI/UX design is supposed to be changed as in other issues raised. Fonts are inconsistent throughout the app and font weight isn't implemented that well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hi @Shreyaskr1409 
I am assigning this task to you. Please ensure you implement all features in best possible way.
And star ⭐ the repo for the better reach. Connet me on :
GitHub : https://github.com/Suryansh1720001
Linkedin : https://www.linkedin.com/in/itssuryansh/

**Comment by Shreyaskr1409** [comment]
Sure. I'm starting to work on it. Including issue #118

**Comment by Shreyaskr1409** [comment]
I have fixed this issue. May I close it?

**Comment by Suryansh1720001** [comment]
No, I'll close the issue after the PR check.
