### ISSUE TITLE
Adding Dependency injection in the app

### ISSUE THREAD

**Issue by harsh2907** [Suryansh1720001/Taaveez#13]
### Is your feature request related to a problem? Please describe.

With the growing features in the app, there should be only single source of trust for the data. So for this purpose we should add Dagger Hilt in the project 

### Describe the solution you'd like

I will add Dagger hilt in the project so kindly assign it to me under GSSOC'23 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yellurividyendra** [comment]
i am GSSOC'23 contributor
i would like to do this project using kotlin
so kindly assign me this project
@codervivek5

**Comment by Suryansh1720001** [comment]
Hello @harsh2907 
Explain to me how Dagger Hit can help here so that I can assign you a task.

**Comment by harsh2907** [comment]
Well when we use a scalable architecture for the application we use dependency injection to make code reusable, easier for testing, improves performance and also it makes code organization, migration and changed in library easier as it promotes single source of truth i.e only one time initialisation of libraries but i would suggest if we first appy MVVM architecture then dagger would work more efficiently either way it would be great for application

**Comment by Suryansh1720001** [comment]
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this.

**Comment by Suryansh1720001** [comment]
@harsh2907 
Any Update?

**Comment by Suryansh1720001** [comment]
not any response
