### ISSUE TITLE
Dark and Light mode not working 

### ISSUE THREAD

**Issue by iampranshu2003** [Suryansh1720001/Taaveez#15]
### What happened?

Light and dark theme is not working in the settings. I want to work on this issue can you please assign me this issue under gssoc tag.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to settings
2. Under Preferences
3. Click on Theme(Dark & Light)
4. No visible change can be seen
```

### Expected behavior

When clicking on light mode the background must change to lighter tone color and the text must change to black color, similarly button color must change to dark.
On switching to dark theme the background color must change to darker tone colors and the text must change to white or lighter tone similarly button colors must change to lighter tone .

### Screenshots

![576](https://github.com/Suryansh1720001/Taaveez/assets/116300962/ad604b70-a3d2-4a11-8604-ea3ec48ba682)
![WhatsApp Image 2023-05-20 at 19 46 25](https://github.com/Suryansh1720001/Taaveez/assets/116300962/d6767557-effb-4b68-aedf-43131c1f1e1f)

No change is visible after switching between light and dark theme

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

samsung galaxy F22

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hi @iampranshu2003,

The application now has both dark mode and light mode functionality implemented. Please review the code and run it from there, not the Play Store one. Feel free to search for any other bugs or enhancement features that can be added. Additionally, don't forget to follow @Suryansh1720001  and star this repository for future use.
