### ISSUE TITLE
Implementation of Robust MVVM architecture in the app and implement basic Create, Read, Update, Delete & deleteAll operations with latest Android API. 

### ISSUE THREAD

**Issue by Ivan2001otp** [Suryansh1720001/Taaveez#16]
### Is your feature request related to a problem? Please describe.

We can implement MVVM architecture that helps to interact with remote  database and local database . Thus helps in data management and presentation logic, resulting in better maintainability and scalability of code-base.

### Describe the solution you'd like

I want to build and implement robust backend that can very helpful in business logic processing and scalability. So please assign this issue to me under GSSOC '23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ivan2001otp** [comment]
![output](https://github.com/Suryansh1720001/Taaveez/assets/95516830/54ed3dba-567c-4b42-8bc0-ab5807a2e742)

**Comment by Suryansh1720001** [comment]
The MVVM architecture has already been assigned to another person. Additionally, the "delete all" option is unnecessary. You can explore other issues and opportunities for contributions.
