### ISSUE TITLE
Light and dark mode , UI Improvement

### ISSUE THREAD

**Issue by HeyfromNandini** [Suryansh1720001/Taaveez#17]
### What happened?

Hello @Suryansh1720001 , I am a GSSOC contributor here , I would like to work on fixing the bug of light and dark mode (isn't working) ; also i would like to improve the ui of the app to make it more eye-pleasing.
Looking forward to useful contributions.....
Thankyou.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
.
```

### Expected behavior

.

### Screenshots

.

### Version

1.1.0 (Default)

### Version (If not available above)

.

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

.

### Additional context

 .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @HeyfromNandini 
Dark-Light mode is functional. Please review the code for running the app in an emulator. Feel free to create new issues following the contributor guidelines.
