### ISSUE TITLE
Dark mode switch doens't work 

### ISSUE THREAD

**Issue by DroidMystic** [Suryansh1720001/Taaveez#21]
### What happened?

The dark mode switch doens't work , it's always in dark mode , i.e we can't switch themes.
I am a Gssoc 23 contributor, please assign me , I'll fix the issue.
Thank you 

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

Theme should change while clicking the switch

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

Galaxy M52 5G, Android 13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DroidMystic** [comment]
Keks

**Comment by DroidMystic** [comment]
🆗

**Comment by Suryansh1720001** [comment]
@DroidMystic 
Dark-Light mode is functional. Please review the code for running the app in an emulator. Feel free to create new issues following the contributor guidelines.
And you can follow me on GitHub @Suryansh1720001 for updates.
