### ISSUE TITLE
Adding Image Along with Text

### ISSUE THREAD

**Issue by Shubhanshu156** [Suryansh1720001/Taaveez#22]
### Is your feature request related to a problem? Please describe.

I would like to add a feature by which user can add images along with text.

### Describe the solution you'd like

In addition to storing poetry, stories, and other written content, users can now seamlessly integrate captivating images that complement their creations. This feature introduces a new level of interactivity, making the reading experience truly immersive and enjoyable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shubhanshu156** [comment]
@Suryansh1720001 Please Assign this issue to me

**Comment by Suryansh1720001** [comment]
@Shubhanshu156 
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app and its theme.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Krishnaraj-shankar** [comment]
I highly appreciate the issue, Usually we people like to add pictures or images to the notes. If the issue is still open I would love to contribute @Suryansh1720001
