### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Suryansh1720001/Taaveez#23]
### Is your feature request related to a problem? Please describe.

![badges](https://github.com/Suryansh1720001/Taaveez/assets/104543751/20c46a99-8a54-4635-a61b-36c5115b84fd)

### Describe the solution you'd like

I want to add readme badges

### Describe alternatives you've considered

PLease assign this issue to me 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by building-the-future** [comment]
PLease assign this issue to me

**Comment by building-the-future** [comment]
Hello sir,
I am a beginner in Android development and want to contribute to a issue. I really liked your project and it has everything that I I want to learn in android development.
Please Assign a Issue to me So that I can Contribute!!!

**Comment by Suryansh1720001** [comment]
@S-ishita 
Document-type contributions are not necessary in this context, as they may not enhance your proficiency in open-source development. I would recommend examining the code for other issues pertaining to coding-related matters. If you require assistance, you can refer to the existing issues that have already been created.
For more info: follow me on socials - 
[LinkedIn](https://linkedin.com/in/itssuryansh/)
@Suryansh1720001 
[Twitter](https://twitter.com/itssuryanshP)

---

Hello @building-the-future 
Thank you for your interest in contributing to our project! We appreciate your enthusiasm as a beginner in Android development. We welcome your participation and encourage you to explore the available issues. Our project covers a wide range of topics that can help you learn and grow in Android development. We look forward to your valuable contributions.
If you require assistance, you can refer to the existing issues that have already been created.
