### ISSUE TITLE
Home page View

### ISSUE THREAD

**Issue by omega-faisal** [Suryansh1720001/Taaveez#24]
### Is your feature request related to a problem? Please describe.

The home page which have the record of writeups looks very simple and basic.
we can also provide multiple colors  for writing in the individual main file.

### Describe the solution you'd like

I can make the  writeup records at home page look better and beautiful by changing their view to square boxes and by implementing different text styles and scripts for Title and content respectively.

### Describe alternatives you've considered

The home page view can be improved by changing the item adapter of this Room Database, I will change the drawable file which is responsible for the view of records and which holds the  share and delete buttons with a Textview.
for the purpose of providing multiple colors to write with I will add a color button which will open a view for selecting colors upon being pressed and when user will select a particular color this color string will be passed to the textview and textview color will be changed to the color the user choosed.

### Additional context

I am adding a screenshot which will depict how the application might look after the changes .
![Appidea](https://github.com/Suryansh1720001/Taaveez/assets/124120325/3b0513fc-1fc9-4ec5-a5fd-d9fbeddc4f31)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanshu942** [comment]
I would like to work on this issue under Gssoc

**Comment by chhavisharma30** [comment]
I would like to work on this issue under Gssoc. I will replicate  the home page view as described in the screenshot.
