### ISSUE TITLE
Any open issues available to contribute? GSSOC23 Contributer here

### ISSUE THREAD

**Issue by s0oraj** [Suryansh1720001/Taaveez#3]
Hi @Suryansh1720001 , i am a GSSOC23 contributer and I would like to resolve any issue you might have.
I have seen this project from project section of GSSOC23

Can you assign some issue?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aditya13s** [comment]
Hi @Suryansh1720001 , I am a GSSOC23 contributor
I'm eager to contribute to this project and utilize my Android development skills. I'm looking for new issues to work on or opportunities to implement new features. If there are any tasks that need assistance or if you have any specific feature requests, I would be happy to contribute.

Please let me know if there are any unassigned issues or if you would like me to propose new features or improvements to the project. I'm open to suggestions and ready to collaborate with the team.

Thank you, and I'm excited to be part of this project!

**Comment by Suryansh1720001** [comment]
@s0oraj @Aditya13s 
Hey guys, there are new issues open for you to check out. Alternatively, you can also take a look at the app itself and discover any bugs or find areas where enhancements can be made.
Additionally, don't forget to follow @Suryansh1720001 and star this repository for future use.
Thank You
