### ISSUE TITLE
Making application more light weight

### ISSUE THREAD

**Issue by Harsh4902** [Suryansh1720001/Taaveez#38]
### Is your feature request related to a problem? Please describe.

As I can see, there are many activities in this application, and we know that activity is a bit heavier than fragment. so we can use fragments in place of activity. So we can convert whole application into single activity multiple fragment architechture,

### Describe the solution you'd like

We can use new navigation framework. By using it, we can navigate through different fragments and make our application more light weight.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
@Harsh4902 
It is not mandatory as I have devised future plans that necessitate the preservation of these files. Therefore, it is advisable to focus on other areas that require contributions from contributors in order to enhance the app with simple, innovative, and distinctive functionalities.
