### ISSUE TITLE
Adding an onboarding experience for new users along with intro slides

### ISSUE THREAD

**Issue by jaivsh** [Suryansh1720001/Taaveez#39]
### Is your feature request related to a problem? Please describe.

The app doesn't have a proper onboarding set up. If done, it would make the users get familiar with the application fairly easily and would make them understand how to use the application properly.

### Describe the solution you'd like

I'd design and implement the intro screens along with proper onboarding, so that when the app would be installed and opened for the first time, the users would be greeted by an automated experience which would acquaint users with app's features and how to use it.

### Additional context

Some sample images for understanding onboarding: 

![](https://camo.githubusercontent.com/bad7e3d3a53cd264e4a4be2383c233ebedca1888d13ad35fe8b67b36e3561072/68747470733a2f2f75706c616e64736f6674776172652e636f6d2f6c6f63616c79746963732f77702d636f6e74656e742f75706c6f6164732f73697465732f34352f323032302f30362f6170702d757365722d6f6e626f617264696e672e706e67)

![](https://camo.githubusercontent.com/7f5681e0a9f58163c9fe6172bf7abcbd2e3afd7618e9f08f6f9c76a66befd9ce/68747470733a2f2f7777772e6461746f636d732d6173736574732e636f6d2f34383239342f313636303839383638362d6d61642d6f6e626f617264696e672d392d696d706163742e706e673f6175746f3d666f726d6174)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hello @jaivsh 
Any update?

**Comment by crsongirkar** [comment]
Hello sir I am Interested in This Task. I have already created some splash screen and onboarding screen.

**Comment by chhavisharma30** [comment]
I want to work on this issue under Gssoc. I have experience in creating onboarding screen.
