### ISSUE TITLE
Any issues available to contribute?

### ISSUE THREAD

**Issue by KrishVerma7** [Suryansh1720001/Taaveez#4]
### Is your feature request related to a problem? Please describe.

Hello sir, I'm GSSOC'23 Contributor, and I have starting learning Android app development in Kotlin a month back. I would love to contribute to your project. Just want some guidance  from you 🙌. Can you please open some issues and assign them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
Hey @KrishVerma7, there are new issues open to check out. Alternatively, you can also take a look at the app itself and discover any bugs or find areas where enhancements can be made.
Additionally, don't forget to follow @Suryansh1720001 and star this repository for future use.
Thank You
