### ISSUE TITLE
[GSSoC'23] Improve the project image dashboard in the Readme file

### ISSUE THREAD

**Issue by anandanmukh** [Suryansh1720001/Taaveez#45]
### Is your feature request related to a problem? Please describe.

- The app screenshots look a little plain and basic. We need to make it more presentable. I just want to make it seem more appealing for anyone visiting the project
- Also, we need to have the presentations in one banner and the screenshots need to be from the google playstore build.
- This is an example of what I can do (from my own repo)
![flutter_projects_1](https://github.com/avinashkranjan/Friday/assets/67072228/5187cd02-6593-44b3-9ecf-f7b9da5c7d5a)

### Describe the solution you'd like

- I would put the images(screenshots) from the Taaveez/graphics folder and add a frame to it, and finally add it to a poster. Doing this, will make the readers feel like they are holding the app in their hands
- I would choose the colour of the background in accordance with the design theme

### Describe alternatives you've considered

We can also add a video scrolling screen for the application.

### Additional context

@avinashkranjan Please assign this to me under the GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this.

**Comment by chhavisharma30** [comment]
I can work on this issue.
