### ISSUE TITLE
Voice typing

### ISSUE THREAD

**Issue by NehaVns** [Suryansh1720001/Taaveez#46]
### Is your feature request related to a problem? Please describe.

Adding a voice typing feature in the application.

### Describe the solution you'd like

I recommend implementing a speech-to-text feature in the application. 

### Describe alternatives you've considered

No alternatives at this point of time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanshu942** [comment]
I would like to work on this issue under Gssoc
