### ISSUE TITLE
Installations file

### ISSUE THREAD

**Issue by utkarsh006** [Suryansh1720001/Taaveez#5]
### Is your feature request related to a problem? Please describe.

- This file will contain all the installation guidelines, written in readme file.
- This issue will enhance Readme and make it look simpler and cleaner.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @Suryansh1720001 , i think @utkarsh006  referencing about creating an installation.md file. As New features keep on adding. complexity of the project may increase to avoid the installation issues in different local system. I would like to add this file to the repo. So, it would help future Contributors to set up project easily in their local system. can you please assign me this issue.

**Comment by Suryansh1720001** [comment]
Hello @utkarsh006,

I wanted to inform you that it is not necessary to add another file for installation. We already have a contribution.md file.
Thank you for your understanding.
