### ISSUE TITLE
Migrate Android App to Single Activity Architecture with Navigation Component

### ISSUE THREAD

**Issue by ashutosh-kumar-kushwaha** [Suryansh1720001/Taaveez#50]
### Is your feature request related to a problem? Please describe.

The project follows multiple activity architecture which has various disadvantages :
1) Code duplication
2) Complex Navigation
3) Difficulty in sharing data from one activity to another
4) Poor performance

### Describe the solution you'd like

I would like to migrate the Android app to a single activity architecture using the Navigation Component provided by the Android Jetpack library. This architectural change will simplify the app's navigation, improve code organization, enhance user experience, and make the app more maintainable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutosh-kumar-kushwaha** [comment]
Please assign this issue to me @Suryansh1720001

**Comment by shreeja5060** [comment]
It involves having a single activity as the container for your app's screens or fragments, with the Navigation Component handling navigation between them. Requesting you to assign this to me as i will be able to solve this and enhance my skills
