### ISSUE TITLE
IMPROVEMENT IN SPLASH SCREEN

### ISSUE THREAD

**Issue by AryanShivva** [Suryansh1720001/Taaveez#51]
### Is your feature request related to a problem? Please describe.

Creating an interactive and nice looking splash screen.

### Describe the solution you'd like

Improved the splash screen into a nice design.
<img width="359" alt="Screenshot 2023-05-31 at 11 43 17 PM" src="https://github.com/Suryansh1720001/Taaveez/assets/124916476/3db6e930-3e8b-452b-a674-8d32abaea1aa">

### Describe alternatives you've considered

I am also trying to add some nice looking animations to the splash screen

### Additional context

Please assign me this task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khan-mujeeb** [comment]
hey is this issue still open, I would like to work on this issue under the gssoc23
