### ISSUE TITLE
Github Action to build app when sending PR

### ISSUE THREAD

**Issue by DevMehta1206** [Suryansh1720001/Taaveez#55]
### Is your feature request related to a problem? Please describe.

integrate github action in order to avoid app breakj after PR merge 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afreen-ahmed12** [comment]
can i do this???? please respond

**Comment by DevMehta1206** [comment]
actually i want to work on this please assign me this @Suryansh1720001

**Comment by Suryansh1720001** [comment]
@DevMehta1206 
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app.

**Comment by afreen-ahmed12** [comment]
Thank you, I will do that.
