### ISSUE TITLE
Fix Text in Readme

### ISSUE THREAD

**Issue by Sriparno08** [Suryansh1720001/Taaveez#58]
### What happened?

In the third bullet point under the 'Technology' section, the 'Studio' word is spelt wrong.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to README.md
2. Scroll down to 'Technology'
3. See error
```

### Expected behavior

The word 'Studoid' needs to be changed to 'Studio'.

### Screenshots

![Screenshot 2023-06-06 175852](https://github.com/Suryansh1720001/Taaveez/assets/89148144/d995f0d7-f3bf-49c4-9b6c-96116e189b81)

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Not Applicable

### Additional context

I would like to contribute as part of GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanisha91** [comment]
Sir i am also interested in this problem.. Can you assign it to mr

**Comment by Suryansh1720001** [comment]
Hey @Sriparno08 @tanisha91 @NANDHINI45,
Document-type contributions are not necessary in this context, as they may not enhance your proficiency in open-source development. I would recommend examining the code for other issues pertaining to coding-related matters. If you require assistance, you can refer to the existing issues that have already been created.
For more info and doubts, you can follow me on socials - 
[LinkedIn](https://linkedin.com/in/itssuryansh/)
@Suryansh1720001 
[Twitter](https://twitter.com/itssuryanshP)
