### ISSUE TITLE
NullPointerException in AddContent method at line 146

### ISSUE THREAD

**Issue by arqam365** [Suryansh1720001/Taaveez#72]
### What happened?

The error message: "FATAL EXCEPTION: main Process: com.itssuryansh.taaveez, PID: 28364 java.lang.NullPointerException at com.itssuryansh.taaveez.Add_New_Content.AddContent$lambda$9(Add_New_Content.kt:146)..."

replace: 
if (PoemDes?.html!!.isNotEmpty()) {

with: 
if (!PoemDes?.html.isNullOrBlank()) {

### Reproduction steps

```bash
Not included 
```

### Expected behavior

When we click on the save button when there no field is given it should say the field is not given. 

### Screenshots

Not available.

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

samsung-sm_f127g

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khan-mujeeb** [comment]
Hii
I would like to work on this issue

**Comment by Suryansh1720001** [comment]
@arqam365 
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app.

**Comment by Suryansh1720001** [comment]
@arqam365 
Any Update?

**Comment by arqam365** [comment]
> @arqam365 Any Update?

updates completed
