### ISSUE TITLE
Request for Addition of Highlight Text Feature

### ISSUE THREAD

**Issue by vibhuti2201** [Suryansh1720001/Taaveez#77]
### Is your feature request related to a problem? Please describe.

The absence of the feature that allows users to highlight crucial information within the content imposes constraints on comprehension and the ability to prioritize data effectively.

### Describe the solution you'd like

- Enable text selection and highlighting functionality.
- Support multiple highlights within the content.
- Provide options to clear highlights.
- Ensure persistence of highlighted text.

### Additional context

Benefits:

- Enhanced usability and user experience.
- Improved comprehension and analysis.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suryansh1720001** [comment]
@vibhuti2201 
Adding a highlight feature to the content page would be a beneficial addition.
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app and its theme.
