### ISSUE TITLE
Request for integrating playback functionality for soothing ASMR Sounds and User-Uploaded Audio: A Request for Enhancement

### ISSUE THREAD

**Issue by vibhuti2201** [Suryansh1720001/Taaveez#82]
### Is your feature request related to a problem? Please describe.

Enhance the user experience in the app by integrating enabled ASMR/user uploaded sound playback and provide a curated collection of soothing ASMR sounds, such as nature sounds and whispering, to create a calming and inspiring environment for users to write poems, stories, and couplets.

### Describe the solution you'd like

Implement a dedicated section with a variety of ASMR sounds, including playback controls for play, pause and volume adjustment. Integrate the ASMR feature seamlessly into the writing interface for a harmonious and productive writing experience.

### Additional context

Expected Benefits:

- Improved Creativity and Focus
- Increased User Engagement and Satisfaction
- Potential for Expansion and Customization

By integrating ASMR sound playback, it provides an elevated writing experience and empowering our users to express their creativity effectively. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vibhuti2201** [comment]
@Suryansh1720001 @Vaibhav2002 Kindly assign this issue to me.

**Comment by Suryansh1720001** [comment]
Hello @vibhuti2201 
I'm assigning you this task for GSSoC'23. You can reach out to me on [LinkedIn](https://www.linkedin.com/in/itssuryansh/) through this link or follow me on [GitHub](https://github.com/Suryansh1720001). Feel free to connect with me regarding this app and its theme.

**Comment by Suryansh1720001** [comment]
Didn't find any response.
