### ISSUE TITLE
Changing the add section text colors , for better visibility to user .

### ISSUE THREAD

**Issue by Chayandev** [Suryansh1720001/Taaveez#9]
### Is your feature request related to a problem? Please describe.

In the add section the title and the description inputs text are Balck in color.

### Describe the solution you'd like

those are not user-friendly visibility sow i want to change those color.

Please assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chayandev** [comment]
@Suryansh1720001 please give me the opportunity the enhancement.

**Comment by Suryansh1720001** [comment]
Could you please provide a template for that? I would like to clarify in which context you are referring to. Is it related to an EditText or something else?
Also, ensure to review the contributor guidelines as well.

**Comment by riya1901** [comment]
please assign it to me.

**Comment by Suryansh1720001** [comment]
@Chayandev 
@riya1901 

Any reply guys or I'll close this issue or assign it to another contributor.

**Comment by Chayandev** [comment]
![Screenshot_2023-05-31-18-12-27-329_com itssuryansh taaveez](https://github.com/Suryansh1720001/Taaveez/assets/91884990/17f8450a-6635-4620-b895-5e1a155826fc)

I want to change this section , the edit text input section color ,, means the color of the text which user will type in that text box ,, it is currently black and background is also blackish so text  is not clearly visible to user so I want to change this one ...

**Comment by Suryansh1720001** [comment]
@Chayandev 
The application is already functioning and has been updated (only in Code). Please review the code and test the application on an emulator. You can also explore other issues that require contributions from contributors.
