### ISSUE TITLE
Bug on click Save button without any content

### ISSUE THREAD

**Issue by Chayandev** [Suryansh1720001/Taaveez#94]
### What happened?

I found one small bug in the code , that while pressing **save button in the add_new_content activity no snackbar is appered and it showing** one black screen(samll time) and get disappred and get back to the mainactivity.

Please assing me this issue @Suryansh1720001 , i will fix it.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1.Click On the + icon to add content
2.Click on save button without adding any content
3.See error
```

### Expected behavior

While There is no content then one snackbar should be appear(which is already implmented in the code but still there is some logical issue), but it is'nt appearing .

### Version

1.1.0 (Default)

### Version (If not available above)

1.1.1

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

POCO M2 Pro , Android 11, screen size 6.75

### Additional context

And one addition thing no so serious although ,in the Toolbar of the Add_new_content Activity there is a sepping issue **invative work** it will be **innovative** 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vaibhav2002** [comment]
@Chayandev can you please attach a video of the bug.

**Comment by Chayandev** [comment]
Sure

**Comment by Chayandev** [comment]
https://github.com/Taaveez/Taaveez-android/assets/91884990/ba6326ec-1c16-4573-b127-c8a6c5d6aaec

while clicking on **save button** without content it's not showing any snakbar ,, **i want to fix this portion.**

**Comment by Vaibhav2002** [comment]
@Chayandev go ahead
