### ISSUE TITLE
margin support attribute add to support older version than api 17

### ISSUE THREAD

**Issue by Deepshikhayadav** [Suryansh1720001/Taaveez#96]
### What happened?

add android:layout_marginLeft="4dp" attribute to support older version than api 17

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

to support older version add margin support attribute

### Version

1.1.0 (Default)

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

andoroid 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by princeraj-pr** [comment]
I want to work on this issue #96 under CodePeak'23
